# Generated by Django 5.1.3 on 2024-11-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
    ]
